### ISSUE TITLE
PaymentTerminalTillService brings exception html error code 415

### ISSUE THREAD

**Issue by danisute** [wallee-payment/wallee-csharp-sdk#11]
Hi, 
I try use the Methode PerformTransaction the PaymentTerminalTillService and become a exception as "HTML Document with Error Code 415" in the Exception Message.
The creation of the Transaction over the TransactionService works well, but the PaymentTerminalTillService with same configuration brings the error 415. I also read the Terminalconfiguration over the PaymentTerminalService to check of the TerminalID is correct, and this showing me corrrect answer.
I was try test the same parameters over the Web Service API Client in the Wallee Documentation, and then its works fine.
The Application-User have at moment Admin rights, then i think its can be not a problem of the permission.
I use, the latest Version 3.01 with .net Framework 4.5.2 (i was also test with 4.6). 
Thanks for checking. 
Kind regards

**Comment by thibault-mambour** [comment]
Hi, this bug was fixed with the release in 12/21
