### ISSUE TITLE
missing service action for update line items

### ISSUE THREAD

**Issue by thornch** [wallee-payment/wallee-csharp-sdk#15]
The **TransactionService** missing function for retreive the object from type "**TransactionLineItemUpdateRequest**"

Regarding the tests in class **Wallee.Test.TransactionServiceTests** the function **UpdateTransactionLineItemsTest()** performs a test like **SearchTest()** (which is commented out by the way)

The object/class TransactionService does not contains a function for retreive and process a LineItemUpdate although there exists a class for it.

Do I missing some infos?
How can I do perform a line item update with this library?

**Comment by sauliususoniswallee** [comment]
Hi @thornch, thank you for your feedback we will look into this with the team

**Comment by thornch** [comment]
The Item "TransactionLineItemUpdateRequest" is obsolete and should be removed.

According updated documentation this action is performed now with "create line item" - and it works as expected.

Referring to doc: https://app-wallee.com/en-us/doc/payment/complete#_edit_line_items_over_the_webservice
> As long as the transaction is not Completed you can change and edit the line items as you like. Use the create line item version operation to update existing line items over the API.
