### ISSUE TITLE
TransactionCreate: Default value for CustomersPresence seems to be wrong

### ISSUE THREAD

**Issue by thornch** [wallee-payment/wallee-csharp-sdk#16]
At creation of a new transaction I do not define the value for "CustomersPresence".
Acording to the docs the default value for "customersPresence" should be "Virtually Present" (and also described in the code):
https://app-wallee.com/en-us/doc/api/web-service#_transaction_create 

Obviously the transaction is created with number if zero "0" and thus the customer's presence is "not present" in the transaction.

Could it be, that the additional setting "EmitDefaultValue=true" produce the default value "0" for integers as the type CustomerPresence is an ENUM of int?
https://github.com/wallee-payment/csharp-sdk/blob/e4bc159219cfa7aecfb1e5402e8c52e4c5da7b20/src/Wallee/Model/TransactionCreate.cs#L79

For my case I've set the value explicit and everything works fine - maybe you want to check this default value yet

**Comment by theodorspringwallee** [comment]
Dear [thornch](https://github.com/thornch)

Sorry for the late response, this issue has been forgotten

Our developer fixed this: https://github.com/wallee-payment/csharp-sdk/blob/master/src/Wallee/Model/TransactionCreate.cs#L79

The `EmitDefaultValue` is now set on `false`, which ends in the correct behaviour (customerPresence="VIRTUAL_PRESENT")

Best regards
