### ISSUE TITLE
Web proxy in ApiClient.RestClient.Options not working

### ISSUE THREAD

**Issue by rafagp-dev** [wallee-payment/wallee-csharp-sdk#21]
Setting up a web proxy for the rest client does not seem to work since version 5.0.1

Code example:

`Startup.cs`
```csharp
public void ConfigureServices(IServiceCollection services) {
    // code...

    var myWalleeConfig = new Configuration(
        configuration.GetValue<string>("Wallee:ApplicationUserID"),
        configuration.GetValue<string>("Wallee:AuthenticationKey")
    );

    myWalleeConfig .ApiClient.RestClient.Options.Proxy = new WebProxy
    {
        Address = new Uri(configuration.GetValue<string>("Proxy:Url")),
        BypassProxyOnLocal = configuration.GetValue<bool>("Proxy:ByPassLocal")
    };

    services.AddSingleton(myWalleeConfig);

    // code...
}
```

Then when calling a service:

```csharp
class MyService {
    private readonly ICustomerService _customerService;

    public MyService (ICustomerService customerService)
    {
            _customerService = customerService;
    }


    public void TestService(CustomerCreate customer)
    {
        _customerService.CreateWithHttpInfo("SpaceId", customer);
    }
}
```

**Comment by theodorspringwallee** [comment]
Dear [rafagp-dev](https://github.com/rafagp-dev)

Please, can you provide us the whole code (with the dependencies you are using).

If you want, you can also write a mail to info@wallee.com to send us this data.

Best regards

**Comment by rafagp-dev** [comment]
I created a repo with project example: https://github.com/rafagp-dev/WalleeExample
The original source code uses the same version of C# and the WebProxy used is this one https://learn.microsoft.com/en-us/dotnet/api/system.net.webproxy?view=net-6.0

This has Wallee package version 5.1.0, if you test this version the calls are not going through the web proxy but if you change to version 4.3.11 the calls goes throught the web proxy.

**Comment by theodorspringwallee** [comment]
Dear [rafagp-dev](https://github.com/rafagp-dev)

Thank you for your information.
We will let you know if we have further information for you.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [rafagp-dev](https://github.com/rafagp-dev)

With our newest release, the proxy use case should work again.

Download for this our newest SDK version as well, look at the documentation to see also the call of the Proxy object: https://github.com/wallee-payment/csharp-sdk#getting-started

Best regards

**Comment by rafagp-dev** [comment]
Hi @theodorspringwallee,

I will update and check it out. Thank you 🙂

Best regards
