### ISSUE TITLE
.net Framework 4.6.2 Support

### ISSUE THREAD

**Issue by phoebusryan** [wallee-payment/wallee-csharp-sdk#22]
Hey there. We're still using .net Framework 4.6.2 with the csharp-sdk 4.3.11 and I just saw that there are newer versions for .net 5.0 etc.

Will you still release updates that are compatible with 4.6.2? The official support for 4.6.2 ends in 2027.

**Comment by theodorspringwallee** [comment]
Dear [phoebusryan](https://github.com/phoebusryan)

We at wallee have an “up-to-date” policy. That means we support our newest version of plugins and SDKs.

Older SDK versions may work, but we only provide BUG fixes to the newest version.

You can check the compatibility on the newest releases: https://github.com/wallee-payment/csharp-sdk/releases
- Update RestSharp to 110.2.0
- Update targetFramework to .NET 6.0
- Update Newtonsoft.Json to 13.0.3
- Update JsonSubTypes to 2.0.1 - Update NUnit to 3.13.3

If you update to our newest SDK version, you probably need to rewrite some parts of the SDK code in your project.

I hope this will answer your questions.

Best regards

**Comment by phoebusryan** [comment]
Thanks for the very fast response. This helped. We will migrate our applications to .net 8 in the next two years.
