### ISSUE TITLE
Cannot send a content-body with this verb-type. Wallee v.7.0.1

### ISSUE THREAD

**Issue by serhiykaramalak** [wallee-payment/wallee-csharp-sdk#23]
We are getting exceptions in new version 7.0.1.  Previous version 7.0.0 works good.
For example, when calling PaymentPageUrl()
var transactionPaymentPageService = new WService.TransactionPaymentPageService(configuration);
var paymentPageUrl = transactionPaymentPageService.PaymentPageUrl(spaceId, transaction.Data.Id);

Exception: Cannot send a content-body with this verb-type.

**Comment by serhiykaramalak** [comment]
Content-Type header shouldn't be used with GET

https://stackoverflow.com/questions/72179255/restsharp-error-cannot-send-a-content-body-with-this-verb-type?rq=3

**Comment by theodorspringwallee** [comment]
Dear [serhiykaramalak](https://github.com/serhiykaramalak)

Are you using .NET 6.0 or higher? (https://github.com/wallee-payment/csharp-sdk#frameworks-supported)

Best regards

**Comment by serhiykaramalak** [comment]
We use .NET Framework 4.8

Content-Type header shouldn't be used with GET. Content-Type is for Request. Could you avoid setting Content-Type with GET method ?

New changes in ApiClient.cs :127  cause an exception .
https://github.com/wallee-payment/csharp-sdk/commit/f950dd58a14c18fa9a5373256c307f99ff646fc4
if (contentType != null)
{
    request.AddHeader("Content-Type", contentType);
}

**Comment by theodorspringwallee** [comment]
Dear [serhiykaramalak](https://github.com/serhiykaramalak)

We also use the newest version (where the code is working), which officially only works with .NET 6.0+, as described here: 
https://github.com/wallee-payment/csharp-sdk#frameworks-supported

Please can you try again your code with .NET 6.0.

If you still have issues then, feel free to create a ticket at info@wallee.com

Best regards
