### ISSUE TITLE
CustomersPresence is mandatory in TransactionCreate constructor while it's an optional parameter

### ISSUE THREAD

**Issue by tomkerkhove** [wallee-payment/wallee-csharp-sdk#3]
The constructor of `TransactionCreate` has an optional parameter for `CustomersPresence` while it is being enforced.

This should be enforced via the signature of the constructor.

**Comment by thomashunziker** [comment]
We will change that. Currently the parameter is required. However as you have noticed correctly we set it with a default value when you do not provide one. This will be included in the next release.

**Comment by tomkerkhove** [comment]
Well to be precise the default value will be null and thus be blocked but I presume you will handle this in the future.

**Comment by adamovic-cw** [comment]
The `CustomersPresence` is now made optional in 1.0.2 release. If it's not provided it will default to `VIRTUAL_PRESENT`. We will also update the documentation on our website, to clarify this behaviour.

**Comment by tomkerkhove** [comment]
Thanks, closing as this has been fixed!
