### ISSUE TITLE
Testing fails due to lack of environment variables

### ISSUE THREAD

**Issue by tomkerkhove** [wallee-payment/wallee-csharp-sdk#5]
It appears like the tests are failing on Travis CI and locally because we don't have the required environment variables.

Are there plans to have a shared application space so that we can run the tests locally/on CI as well?

Example in #4

**Comment by thomashunziker** [comment]
It would be good if we do not need to publish any secrets. Currently we feed in the secrets through the CI server. One option would be to have a file with the credentials. This file is by default not checked in. When we lookup the credentials we first try to use those from the file. If they are not present we use those from the environment. Would that be an option for you?

**Comment by tomkerkhove** [comment]
That would be good for me. You could include a tokenized app.config for the test project so that I can change the values for local testing.

Docs on this would make that easier as well, but not mandatory.

**Comment by adamovic-cw** [comment]
Hi Tom,

I have added App.config file to the test project. The config file contains the public test user account which can be used only for transaction processing.
You can either use the already provided test account or you can sign up and create your own. 
Hope this helps.

**Comment by tomkerkhove** [comment]
@adamovic-cw, this is perfect thank you!
Closing as this fixes the issue.
