### ISSUE TITLE
EntityQuery only has private setters

### ISSUE THREAD

**Issue by tomkerkhove** [wallee-payment/wallee-csharp-sdk#6]
`EntityQuery` only has private setters which blocks us from using it.

https://github.com/wallee-payment/wallee-csharp-sdk/blob/master/src/Customweb.Wallee/Model/EntityQuery.cs

**Comment by adamovic-cw** [comment]
You are right, all `EntityQuery*.cs` models are read-only. 
I will fix this and make a new release.

**Comment by adamovic-cw** [comment]
The new version, which fixes this issue, has been released. It will take some time until package is indexed by NuGet and available for install.
