### ISSUE TITLE
Problems with Postfinance

### ISSUE THREAD

**Issue by MrBalabanS** [wallee-payment/wallee-csharp-sdk#8]
Hi All
I am using csharp-sdk with postfinance. Everything seems to working fine until i see the payment methods, when I choose one (with a click) postfinance redirects me to the given failedUrl. There is no error and no entry in the transactionlog in my Dashboard (when i cancel the transaction without choosing payment method it appears as cancelled), what could be the problem? 
I am aware of the fact, that this could be an error by misconfiguration but postfinance - Helpdesk is not very helpful at the moment.

sincerely

![image](https://user-images.githubusercontent.com/50504170/85605351-5c47bc00-b652-11ea-9282-a2b4a398b2a7.png)

**Comment by thomashunziker** [comment]
Dear Balaban,

It could be that you invoked the API with invalid customer data. However please ask the PostFinance Helpdesk as they are in charge of this.

Regards,
Thomas
