### ISSUE TITLE
Assembly not strong named signed

### ISSUE THREAD

**Issue by bubavanhalen** [wallee-payment/wallee-csharp-sdk#9]
In order to use the NuGet in a solution where the projects are signed to avoid assembly conflicts the assembly output must be signed. 

https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named

**Comment by vttn** [comment]
Hello @bubavanhalen,

We have released a signed version for Wallee 2.2.0 moving forward.

https://www.nuget.org/packages/Wallee/

Regards,
@vttn
